version: '3.8'

services:

  redis-session:
    image: redis:latest
    container_name: redis-session
    ports:
      - "6379:6379"
    volumes:
      - redis-session-data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6380:6379"
    volumes:
      - redis-cache-data:/data
    command: redis-server --appendonly no --maxmemory 1gb --maxmemory-policy volatile-lru
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  redis-session-data:
  redis-cache-data:
  prometheus_data:
  grafana_data: