version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    ports:
      - "8500:8500"      # UI 및 API
      - "8600:8600/udp"  # DNS 인터페이스
    volumes:
      - consul-data:/consul/data
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - discovery-network
      - app-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 30s
      timeout: 10s
      retries: 5

  consul-exporter:
    image: prom/consul-exporter:latest
    container_name: consul-exporter
    command:
      - '--consul.server=consul:8500'
    networks:
      - discovery-network
    depends_on:
      - consul

  # ===== etcd - 분산 키-값 저장소 (주석 처리됨) =====
  # etcd:
  #   image: bitnami/etcd:3.5
  #   container_name: etcd
  #   ports:
  #     - "2379:2379"
  #     - "2380:2380"
  #   environment:
  #     ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
  #     ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
  #     ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
  #     ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
  #     ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380
  #     ETCD_INITIAL_CLUSTER_STATE: new
  #     ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
  #     ALLOW_NONE_AUTHENTICATION: "yes"
  #   volumes:
  #     - etcd-data:/bitnami/etcd
  #   networks:
  #     - discovery-network
  #     - app-network
  #   healthcheck:
  #     test: ["CMD", "etcdctl", "endpoint", "health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # ===== etcd UI (주석 처리됨) =====
  # etcd-viewer:
  #   image: nikfoundas/etcd-viewer
  #   container_name: etcd-viewer
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     ETCD_URL: http://etcd:2379
  #   networks:
  #     - discovery-network
  #   depends_on:
  #     - etcd

  # ===== 예시 등록 서비스 =====
  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip="localhost" consul://consul:8500
    networks:
      - discovery-network
    depends_on:
      - consul
    restart: unless-stopped

networks:
  discovery-network:
    driver: bridge
  app-network:
    external: true

volumes:
  consul-data:
  etcd-data: