server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alarm_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

opensearch:
  host: localhost
  port: 9200
  username: admin
  password: admin
  scheme: http
